### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/carr-mcclellan#68]
Converting checklist in #57 into GitHub issue. Some items will get spun out into more granular issues, and may be marked as checked here with a related issue number following.
### Functionality
- [x] **Browser compatability**: depends on project (see #69)
- [x] **favicon** Obvious, but this can be missed. (see #66)
- [x] **Home screen icon**: Create an iOS home screen icon. Tutorial (see #66)
- [x] **Logo**: Does the logo link to the index page?
- [x] **404 pages**: Check you have these in place, make sure they signpost ways for a user to get back into the site or direct them to pages of interest with relevant links.
- [x] **Forms**: Make sure they aren't sending to spam mail boxes, or returning an error once submitted and include a thank you state once a form is submitted so a visitor knows it is sent. Above all else make sure the clients email address is specified when the site goes live.
- [x] **Forms**: Check validation state and field errors on forms.
- [x] **Links**: Do internal page links work? Do all external links work and do they open in a new tab if so intended?
- [x] **Social links**: check that social media buttons are sharing the proper content and images. See this thread for more information. (see #71)
### Content
- [x] **Delete sample content**: Obvious, but often missed.
### Sitemaps

Make sure you include sitemaps. These help search engines correctly index your website during the crawling process.
- [x] **HTML sitemaps or footer navigation**: Although not as common practice as they were, this form of sitemap can have its benefits in helping visitors see a complete overview of the sites pages. Links for these are normally found in the footer of a site. (see #38)
- [x] **XML sitemaps**: These are only ever used by search engines such as Google, Bing and Yahoo. Create an XML Sitemap easily and submit it via Webmaster Tools. These will then be used to inform search engines about the pages you have published.
### Performance

A faster site is a better ranking site. You'll also lower bounce rates on pages if you can reduce load times - who wants to wait for pages to load?
- [x] **Check site speed**: You can use services such as Google Page Speed or Blame Stella to check the load times of your site's pages.
- [x] **Minify scripts & styles**: create minified version of scripts and styles for faster page loading. (see #67)
- [x] **Retina ready**: incorporate @2x versions of images. Also consider integrating Retina.js
### SEO

This list is by no means extensive and if you want to learn more then we recommend reading more from these recent articles Search Engine Optimization FAQ and A Web Designer's SEO Checklist.
- [x] **WordPress SEO by Yoast**: Install this Wordpress plugin if the client desires more granular control of SEO.
- [x] **Page titles & descriptions**: Do all the templates have the necessary page titles and meta data based on your keyword research? When focusing on a particular keyword try and get these to the front of descriptions and look at using both singular and plural forms.
### Analytics
- [x] **Monitoring**: With good SEO in place use tracking codes to measure this. Tools such as Google Analytics (free) or services such as Hubspot, GoSquared or KISSmetrics (paid) will give valuable feedback.
### Security
- [x] **Protect sensitive pages**: Protect any sensitive pages or folders from being indexed on search engines by putting in place robots.txt files and by excluding them from within Webmaster Tools. Also consider whether you need to use an .htaccess file to disable folder view within directories.
- [x] <del>**Security certificates**: When developing an eCommerce website, or a site that handles sensitive visitor information, the level of security will be paramount. Make sure to use protocols such as SSL encryption to protect against unwanted information theft. It has also been proven that displaying seals such as TRUSTe, can increase the credibility of a site.</del>
### Backups
- [ ] **Backup site to local server**: Make a copy of the site to store in the clients folder on the server.
