### ISSUE TITLE
Post-Launch Checklist

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/carr-mcclellan#70]
### Summary sheet

The client should be provided with a document summarizing AT LEAST the following:
- [x] **CMS login info**
- [x] **FTP server and login credentials**
- [x] **MySQL database login info**
- [x] **Analytics login info**
- [x] **Web font host and login info**
### Legal
- [x] **Image/content rights**: Clearly state that any supplied content or imagery that is handled by you remains the clients responsibility. Make clear that you will not be held liable for publishing content and images that they do not have the rights to use. Also educate the client that they should be using images or content that are either paid for or they have the rights to use.
- [x] **Check links**: Make sure links on live site are not redirecting back to DEV site.
### Configuration

Make sure that plugins and settings are configured correctly.
- [x] **Yoast SEO**: Double check settings, ensure Facebook og:image is right
- [x] **Google Analyticator**: Add UA id, ensure pages are being tracked
- [x] **Backups**: Ensure backup (weekly or monthly) is scheduled with host (#83)
### Other
- [x] **Site speed**: double-check performance under production configuration
